### ISSUE TITLE
Kindly add the user guides 

### ISSUE THREAD

**Issue by aravinthk00** [sidvenu/KaTeXView#1]
Readme or User guides helpful for me.

**Comment by sidvenu** [comment]
Hey @aravinthk00

The usage is mostly similar to [sidvenu/MathJaxView](https://github.com/sidvenu/MathJaxView).

Check out the example build of MathJaxView: https://github.com/sidvenu/MathJaxView/tree/master/mathjaxtest/

to understand how to integrate KaTeXView.
